force-app/main/default/objects/Color__c/Color__c.object-meta.xml
<CustomObject>
    <label>Color</label>
    <nameField>
        <label>Color Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Icon__c/Icon__c.object-meta.xml
<CustomObject>
    <label>Icon</label>
    <nameField>
        <label>Icon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Icons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Icon__c/fields/DefaultColor__c.field-meta.xml
<CustomField>
    <fullName>DefaultColor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Color of the the Pixels when the Icon is first created.</description>
    <inlineHelpText>The Color of the the Pixels when the Icon is first created.</inlineHelpText>
    <label>Default Color</label>
    <referenceTo>Color__c</referenceTo>
    <relationshipLabel>Default Color Icons</relationshipLabel>
    <relationshipName>DefaultColorIcons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Icon__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Icon__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pixel__c/Pixel__c.object-meta.xml
<CustomObject>
    <label>Pixel</label>
    <nameField>
        <displayFormat>PIXEL-{00000000}</displayFormat>
        <label>Pixel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pixels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pixel__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Color</label>
    <referenceTo>Color__c</referenceTo>
    <relationshipLabel>Pixels</relationshipLabel>
    <relationshipName>Pixels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pixel__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <referenceTo>Icon__c</referenceTo>
    <relationshipName>Pixels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Pixel__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <externalId>true</externalId>
    <label>Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pixel__c/fields/X__c.field-meta.xml
<CustomField>
    <fullName>X__c</fullName>
    <label>X</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pixel__c/fields/Y__c.field-meta.xml
<CustomField>
    <fullName>Y__c</fullName>
    <label>Y</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IconPixelBatch.cls
/*
Icon__c i = [select Id, Width__c, Height__c, DefaultColor__c from Icon__c where Id = 'a021900000DYiDXAA1' limit 1];
IconPixelBatch b = new IconPixelBatch();
b.icon = i;
Database.executeBatch(b);
*/

public with sharing class IconPixelBatch implements Database.Batchable<sObject> {
    
    public Icon__c icon;

    public Iterable<sObject> start(Database.BatchableContext context) {

        List<Pixel__c> pixels = new List<Pixel__c>();
        
        Integer idx = 0;

        for(Integer r = 0; r < this.icon.Width__c; r++) {
            for(Integer c = 0; c < this.icon.Height__c; c++) {
                pixels.add(new Pixel__c(
                    X__c = r,
                    Y__c = c,
                    Color__c = this.icon.DefaultColor__c,
                    Icon__c = this.icon.Id,
                    Index__c = idx
                ));
                idx++;
            }
        }

        return pixels;
    }

    public void execute(Database.BatchableContext context, List<sObject> scope) {
        insert scope;
    }

    public void finish(Database.BatchableContext context) {
        // TODO: check for another icon request
    }
    
}