force-app/main/default/objects/Color__c/Color__c.object-meta.xml
<CustomObject>
    <label>Color</label>
    <nameField>
        <label>Color Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Icon__c/Icon__c.object-meta.xml
<CustomObject>
    <label>Icon</label>
    <nameField>
        <label>Icon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Icons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Icon__c/fields/DefaultColor__c.field-meta.xml
<CustomField>
    <fullName>DefaultColor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Color of the the Pixels when the Icon is first created.</description>
    <inlineHelpText>The Color of the the Pixels when the Icon is first created.</inlineHelpText>
    <label>Default Color</label>
    <referenceTo>Color__c</referenceTo>
    <relationshipLabel>Default Color Icons</relationshipLabel>
    <relationshipName>DefaultColorIcons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Icon__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Icon__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pixel__c/Pixel__c.object-meta.xml
<CustomObject>
    <label>Pixel</label>
    <nameField>
        <displayFormat>PIXEL-{00000000}</displayFormat>
        <label>Pixel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pixels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pixel__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Color</label>
    <referenceTo>Color__c</referenceTo>
    <relationshipLabel>Pixels</relationshipLabel>
    <relationshipName>Pixels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pixel__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <referenceTo>Icon__c</referenceTo>
    <relationshipName>Pixels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Pixel__c/fields/X__c.field-meta.xml
<CustomField>
    <fullName>X__c</fullName>
    <label>X</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pixel__c/fields/Y__c.field-meta.xml
<CustomField>
    <fullName>Y__c</fullName>
    <label>Y</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IconService.cls
public with sharing class IconService {
    
    public static void createIconPixels(Icon__c icon) {
        
        List<Pixel__c> pixels = new List<Pixel__c>();
        
        for(Integer r = 0; r < icon.Width__c; r++) {
            for(Integer c = 0; c < icon.Height__c; c++) {
                pixels.add(new Pixel__c(
                    X__c = r,
                    Y__c = c,
                    Color__c = icon.DefaultColor__c,
                    Icon__c = icon.Id
                ));
            }
        }

        insert pixels;

    }

}

/*
Icon__c i = new 
*/